FROM node:20-bullseye AS deps
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci

FROM deps AS build
COPY tsconfig.json ./
COPY database ./database
COPY prisma ./prisma
COPY serverless ./serverless
COPY serverless/student-queue/dequeue/llm-instructions ./dist/serverless/student-queue/dequeue/llm-instructions

COPY prisma.config.ts prisma.config.ts

ARG DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy"
ENV DATABASE_URL=$DATABASE_URL

RUN npx prisma generate 
RUN npm run build

FROM build AS prune
RUN npm prune --omit=dev

FROM public.ecr.aws/lambda/nodejs:20 AS runner
WORKDIR ${LAMBDA_TASK_ROOT}

COPY --from=prune /app/node_modules ./node_modules
COPY --from=build /app/dist ./dist
COPY --from=build /app/prisma ./prisma
CMD ["dist/serverless/student-queue/handler.functionHandler"]